server:
  port: 8085

jwt:
  secret: 23data3pirate809

customers:
  number: 1
  load: true

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: thedatapirates.cashplan@gmail.com
    password: cukegrhlbmjunjml

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true